title: "LCSPP-AVHRR"
description: >
  The Long-term Continuous SIF-informed Photosynthesis Proxy from AVHRR surface reflectance (LCSPP-AVHRR) provides a globally consistent, biweekly dataset of photosynthetic activity spanning 1982 to 2000 at 0.05° spatial resolution. Version 3.2 of the dataset is constructed by calibrating AVHRR surface reflectance bands against MODIS during their overlapping period (2001–2023), followed by training a neural network to emulate satellite-derived SIF from OCO-2. The LCSPP-AVHRR dataset captures vegetation dynamics with higher fidelity than traditional vegetation indices (e.g., NDVI, kNDVI, NIRv) and is suitable for long-term GPP proxy estimation. All data are provided in NetCDF format with two files per month to represent biweekly intervals.

recipes:
  - id: "LCSPP-AVHRR"
    object: "recipe:LCSPP-AVHRR"

provenance:
  providers:
    - name: "Columbia University"
      description: "Primary research institution developing the neural network and coordinating data integration"
      roles:
        - producer
        - research institution
      url: https://climate.columbia.edu/

    - name: "Seoul National University"
      description: "Partner institution contributing AVHRR processing and MODIS calibration"
      roles:
        - data provider
        - research institution
      url: https://en.snu.ac.kr/

    - name: "Zenodo"
      description: "Permanent archive hosting the LCSPP-AVHRR dataset and associated resources"
      roles:
        - host
      url: https://zenodo.org/doi/10.5281/zenodo.14568024

license: "Creative Commons Attribution 4.0 International (CC BY 4.0)"

citation:
  - authors: "Fang, J., Lian, X., Ryu, Y., Jeong, S., Jiang, C., Gentine, P."
    year: 2025
    title: "Long-term SIF-informed Photosynthesis Proxy derived from AVHRR surface reflectance"
    journal: "In prep"
    doi: "10.5281/zenodo.14568024"

contact:
  email: "jianing.fang@columbia.edu"

maintainers:
  - name: "Jianing Fang"
    github: "JianingFang"
  - name: "Mitra Cattry"
    github: "mitraA90"
